name: TALA530B
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.12
  - jupyterlab=4.2.5
  - jupyterlab-latex=4.0
  - matplotlib
  - numpy
  - pandas=2.2.3
  - python=3.11
  - scipy
  - seaborn=0.13
  - scikit-learn
