name: python-M2TTD-environment
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.12
  - jupyterlab=4.2.5
  - jupyterlab-latex=4.0
  - lxml
  - matplotlib=3.7
  - nltk=3.8
  - numpy=1.25
  - pandas
  - python=3.11
  - scikit-learn=1.3
  - scipy=1.11
  - seaborn=0.12
  - pip
  - pip:
    - googletrans==4.0.0rc1