[project]
name = "TALA530B"
version = "1.0.0"
description = "Resources for Master TeTraDom, second degree, at Inalco."
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
beautifulsoup4 = "4.12.*"
jupyterlab = "4.2.*"
jupyterlab-latex = "4.*"
matplotlib = "3.*"
nltk = "3.*"
numpy = "1.25.*"
pandas = "2.*"
python = "3.11.*"
scikit-learn = "1.3.*"
scipy = "1.11.*"
seaborn = "0.13.*"
