[project]
name = "TALA530B"
version = "1.0.0"
description = "Resources for Master TeTraDom, second degree, at Inalco."
authors = ["Alexandre Roulois <alexandre.roulois@u-paris.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = "4.2.*"
jupyterlab-latex = "4.*"
python = "3.11.*"
